UI banner & chakra theme
Levl-Health/provider-portal pull request #17
Opened 2023-02-20 21:04 UTC by jjmakes

Created Chakra theme with Levl color palette & fonts. Created basic banner & two pages (HCP & Provider Dashboard)

2023-02-20 22:19 UTC, Jayhawk416 approved these changes
Everything looks as it should, this is ok to merge into main

2023-02-20 22:29 UTC, iambillmccann requested changes

2023-02-20 22:29 UTC, iambillmccann commented on web/src/Routes.js
> +import BannerLayout from './layouts/BannerLayout/BannerLayout'
You should use 'src/layouts/BannerLayout/BannerLayer' ... importing from the src folder is a Redwood best practice.

2023-02-20 22:29 UTC, iambillmccann commented on web/src/components/Navbar.js
> +          <ButtonGroup>
The "menu item" links in the Figma design are placeholders. We will not be implementing any features for these in the capstone. You can remove all of these including the dropdown.

2023-02-20 22:29 UTC, iambillmccann commented on web/src/layouts/BannerLayout/BannerLayout.stories.js
> +import BannerLayout from './BannerLayout'
Import from the src folder. VSCode intellisense will find the folder for you. Make sure you have the prettier and linting installed and on.

2023-02-20 22:29 UTC, iambillmccann commented on web/src/layouts/BannerLayout/BannerLayout.test.js
> +import BannerLayout from './BannerLayout'
Import from the src folder. VSCode intellisense will find the folder for you. Make sure you have the prettier and linting installed and on.

2023-02-20 22:29 UTC, iambillmccann commented on web/src/pages/HcpDashboardPage/HcpDashboardPage.stories.js
> +import HcpDashboardPage from './HcpDashboardPage'
Import from the src folder. VSCode intellisense will find the folder for you. Make sure you have the prettier and linting installed and on.

2023-02-20 22:29 UTC, iambillmccann commented on web/src/pages/HcpDashboardPage/HcpDashboardPage.test.js
> +import HcpDashboardPage from './HcpDashboardPage'
Import from the src folder. VSCode intellisense will find the folder for you. Make sure you have the prettier and linting installed and on.

2023-02-20 22:29 UTC, iambillmccann commented on web/src/pages/ProviderDashboardPage/ProviderDashboardPage.test.js
> +import ProviderDashboardPage from './ProviderDashboardPage'
Import from the src folder. VSCode intellisense will find the folder for you. Make sure you have the prettier and linting installed and on.

2023-02-20 22:33 UTC, iambillmccann commented
It looks like CRLF have been added to line endings in at least some of these files (I did not check every one). Is someone developing in Windows? Regardless, be sure to set line ending to LF (and **not** CRLF).

2023-02-20 22:39 UTC, iambillmccann requested changes

2023-02-20 22:39 UTC, iambillmccann commented on web/src/App.js
> +import { ChakraProvider, ColorModeScript, extendTheme } from '@chakra-ui/react'
extendTheme is not used, you should remove the import.

2023-02-23 11:29 UTC, iambillmccann approved these changes

2023-02-23 11:34 UTC, merged